version: 0.0
os: linux
files:
  - source: public/index.html
    destination: /var/www/html/resume-management
hooks:
  BeforeInstall:
    - location: scripts/test-before.sh
      runas: root
  AfterInstall:
    - location: scripts/test-after.sh
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      runas: root
