version: 0.0
os: linux
files:
  - source: /home/ec2-user/reactjs-demo/build/
    destination: /var/www/html/resume-management
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      runas: root
  AfterInstall:
    - location: scripts/clean-data.sh
  ApplicationStart:
    - location: scripts/start_server.sh
  ApplicationStop:
    - location: scripts/stop_server.sh
