version: 0.0
os: linux
files:
  - source: public/index.html
    destination: /var/www/html/resume-management
hooks:
  BeforeInstall:
    - location: scripts/git_command.sh
    - location: scripts/build_frontend.sh
    - location: scripts/build_backend.sh
      runas: root
  AfterInstall:
    - location: scripts/deploy_frontend.sh 
    - location: scripts/deploy_backend.sh
    - location: scripts/clean.sh
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      runas: root
